### ISSUE TITLE
encountered error while runningf0

### ISSUE THREAD

**Issue by YolandaFeng1995** [oxygen-dioxide/pyvogen-docs#2]
f0=model.run([model.get_outputs()[0].name],xs)[0]
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Mul node. Name:'' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/math/element_wise_ops.h:497 void onnxruntime::BroadcastIterator::Init(ptrdiff_t, ptrdiff_t) axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension other than 1. 1262 by 1263

**Comment by oxygen-dioxide** [comment]
可以提供出现该错误时的代码吗?

**Comment by oxygen-dioxide** [comment]
如果你是在运行 [高级对象操作.ipynb](https://github.com/oxygen-dioxide/pyvogen-docs/blob/main/%E9%AB%98%E7%BA%A7%E5%AF%B9%E8%B1%A1%E6%93%8D%E4%BD%9C.ipynb) 时出现这个错误，这是教程中故意这样做，以演示用户错误输入的结果。PyVogen目前还没有开发对错误输入的过滤与提示功能。由于上游项目[vogen.client](https://github.com/aqtq314/Vogen.Client)有重构计划，此功能处于搁置状态。

**Comment by YolandaFeng1995** [comment]
for Lyric,Pitch,On,Dur in zip(SynLyrics,SynPitches,SynOns,SynDur):
                    print('check notelist',Lyric,Pitch,On,Dur)
                    n = vogen.VogNote(pitch=Pitch, lyric=Lyric, on=int(On), dur=int(Dur))
                    Notes.append(n)
            utt = vogen.VogUtt(singerId="Gloria", romScheme="man", notes=Notes)
            file = vogen.VogFile(utts=[utt], bpm0=80, timeSig0='6/8')
            file.lyrictorom()
            synth.synth(file)
---------------------------------------------------------
check notelist 二 67 2640.0 240
check notelist 西 71 2880.0 240
check notelist 如 74 3120.0 24.0
错误输入的意思是--》“如”的duration有问题所以报错了？

**Comment by oxygen-dioxide** [comment]
请提供完整的代码，包括前面导入库，定义SynLyrics,SynPitches,SynOns,SynDur的代码，就是复制到python里面能直接把bug复现出来的。

**Comment by oxygen-dioxide** [comment]
尝试将你的代码补全为以下代码：
```
SynLyrics="二西如"
SynPitches=[67,71,74]
SynOns=[2640.0,2880.0,3120.0]
SynDur=[240,240,24.0]
Notes=[]
import vogen
from vogen import synth

for Lyric,Pitch,On,Dur in zip(SynLyrics,SynPitches,SynOns,SynDur):
    print('check notelist',Lyric,Pitch,On,Dur)
    n = vogen.VogNote(pitch=Pitch, lyric=Lyric, on=int(On), dur=int(Dur))
    Notes.append(n)

utt = vogen.VogUtt(singerId="Gloria", romScheme="man", notes=Notes)
utt.lyrictorom()
file = vogen.VogFile(utts=[utt], bpm0=80, timeSig0='6/8')
file.lyrictorom()
synth.synth(file)
```

在我电脑上是另一个地方报错（应该是没有关系的另一个bug，下个版本会修复）
```
check notelist 二 67 2640.0 240
check notelist 西 71 2880.0 240
check notelist 如 74 3120.0 24.0
  0%|                                                                                            | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\lin\Desktop\vogentest.py", line 18, in <module>
    synth.synth(file)
  File "E:\Python39\lib\vogen\synth\__init__.py", line 72, in synth
    trackwave[uttoffset:uttoffset+len(uttwave)]+=uttwave
ValueError: operands could not be broadcast together with shapes (78829,) (78939,) (78829,)
```
